// <auto-generated />
using System;
using ArtWebshop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtWebshop.Data.Migrations.Products
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20210806150507_Decimal conversion control for Product all decimal properties")]
    partial class DecimalconversioncontrolforProductalldecimalproperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArtWebshop.Models.Artist", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArtistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            ArtistId = "7bd6641e-853e-4194-bfe4-98e7d74d4c86",
                            ArtistName = "Leonardo da Vinci",
                            UserId = "userId"
                        },
                        new
                        {
                            ArtistId = "617c2263-cf15-4609-9b69-c267a61f2a36",
                            ArtistName = "Leonardo da Vinci",
                            UserId = "userId"
                        },
                        new
                        {
                            ArtistId = "d969538a-e82e-4e3e-9dcf-2068f031024d",
                            ArtistName = "Edvard Munch",
                            UserId = "userId"
                        },
                        new
                        {
                            ArtistId = "aaed5a19-d2db-4842-9628-0083d920a9a0",
                            ArtistName = "Vincent van Gogh",
                            UserId = "userId"
                        });
                });

            modelBuilder.Entity("ArtWebshop.Models.ArtistRow", b =>
                {
                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArtistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RowId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ProductId");

                    b.ToTable("ArtistRows");
                });

            modelBuilder.Entity("ArtWebshop.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BillingCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingStreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryStreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ArtWebshop.Models.OrderRow", b =>
                {
                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RowId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderRows");
                });

            modelBuilder.Entity("ArtWebshop.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArtistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaintingOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "7f847eb4-7fdc-45c3-a937-e48c8d25d4c0",
                            ArtistId = "7bd6641e-853e-4194-bfe4-98e7d74d4c86",
                            Category = "Print",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1503),
                            Height = 53,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "Mona Lisa, also called Portrait of Lisa Gherardini, wife of Francesco del Giocondo, Italian La Gioconda, or French La Joconde, oil painting on a poplar wood panel by Leonardo da Vinci, probably the world’s most famous painting. It was painted sometime between 1503 and 1519, when Leonardo was living in Florence, and it now hangs in the Louvre Museum, Paris, where it remained an object of pilgrimage in the 21st century. The sitter’s mysterious smile and her unproven identity have made the painting a source of ongoing investigation and fascination.",
                            PictureLink = "/Images/Originals/Paintings/Mona Lisa.jpg",
                            Price = 50.50m,
                            ShortDescription = "A mysterious woman",
                            Stock = 15,
                            Style = "Oil on wood Panel",
                            ThumbnailLink = "/Images/Originals/Thumbnails//Mona Lisa (thumb).jpg",
                            Title = "Mona Lisa.jpg",
                            Width = 77
                        },
                        new
                        {
                            ProductId = "7d4f87d9-b555-4872-aa3c-ca946cd4ccef",
                            ArtistId = "617c2263-cf15-4609-9b69-c267a61f2a36",
                            Category = "Print",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1495),
                            Height = 460,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "Leonardo Da Vinci",
                            PictureLink = "/Images/Originals/Paintings/The Last Supper.jpg",
                            Price = 33.00m,
                            ShortDescription = "The last supper",
                            Stock = 3,
                            Style = "Olja på duk",
                            ThumbnailLink = "/Images/Originals/Thumbnails/Nattvarden (thumb).jpg",
                            Title = "The Last Supper.jpg",
                            Width = 880
                        },
                        new
                        {
                            ProductId = "7f11d7ff-6886-4c35-8bab-be4e95a0b78d",
                            ArtistId = "d969538a-e82e-4e3e-9dcf-2068f031024d",
                            Category = "Print",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1903),
                            Height = 460,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "",
                            PictureLink = "/Images/Originals/Paintings/Skriet.jpg",
                            Price = 15.505m,
                            ShortDescription = "Edvard Munch",
                            Stock = 150,
                            Style = "Olja, tempera och pastell på papp",
                            ThumbnailLink = "/Images/Originals/Thumbnails/Skriet (thumb).jpg",
                            Title = "Skriet.jpg",
                            Width = 880
                        },
                        new
                        {
                            ProductId = "5242d9ab-3637-4226-b424-375f3a906191",
                            ArtistId = "aaed5a19-d2db-4842-9628-0083d920a9a0",
                            Category = "Print",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1882),
                            Height = 460,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "",
                            PictureLink = "/Images/Originals/Paintings/Utsliten.jpg",
                            Price = 18.505m,
                            ShortDescription = "Vincent van Gogh",
                            Stock = 5,
                            Style = "Postexpressionism: Teckning penna på vattenfärgat papper",
                            ThumbnailLink = "/Images/Originals/Thumbnails/Utsliten (thumb).jpg",
                            Title = "Utsliten.jpg",
                            Width = 880
                        });
                });

            modelBuilder.Entity("ArtWebshop.Models.ArtistRow", b =>
                {
                    b.HasOne("ArtWebshop.Models.Artist", "Artist")
                        .WithMany("ArtistRows")
                        .HasForeignKey("ArtistId");

                    b.HasOne("ArtWebshop.Models.Product", "Product")
                        .WithMany("ArtistRows")
                        .HasForeignKey("ProductId");

                    b.Navigation("Artist");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ArtWebshop.Models.OrderRow", b =>
                {
                    b.HasOne("ArtWebshop.Models.Order", "Order")
                        .WithMany("OrderRows")
                        .HasForeignKey("OrderId");

                    b.HasOne("ArtWebshop.Models.Product", "Product")
                        .WithMany("OrderRows")
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ArtWebshop.Models.Product", b =>
                {
                    b.HasOne("ArtWebshop.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("ArtWebshop.Models.Artist", b =>
                {
                    b.Navigation("ArtistRows");
                });

            modelBuilder.Entity("ArtWebshop.Models.Order", b =>
                {
                    b.Navigation("OrderRows");
                });

            modelBuilder.Entity("ArtWebshop.Models.Product", b =>
                {
                    b.Navigation("ArtistRows");

                    b.Navigation("OrderRows");
                });
#pragma warning restore 612, 618
        }
    }
}
